#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
parameter0() {
    dig www."$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain www is a " $4 " record and points to " $5}' | tail -n -1
    dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}' | tail -n -1
    dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}' | tail -n -1
    dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}' | tail -n -1
}

parameter1(){
    dig "$aux" | grep -A1 'ANSWER SECTION:' | awk -v var=$aux2 '{print "The subdomain " var " is a " $4 " record and points to " $5}' | tail -n -1
}

if [[ $# -lt 2 ]];
then
{
    parameter0 "$1"
}
else
{
    aux=$2.$1
    aux2=$2
    parameter1 "$aux $aux2"
}
fi
