#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo bash -c 'echo "Holberton School" > /var/www/html/index.nginx-debian.html'

