#!/usr/bin/env bash
#Install nginx web server
./1-install_nginx_web_server
sed -i "43s%location / {%location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;%g" /etc/nginx/sites-available/myAppConf
service nginx restart

