#!/usr/bin/env bash
#Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sed -i "43s%location / {%location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;%g" /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html
sed -i "49i\ \n\terror_page 404 /404.html;\n\tlocation /404{\n\t\troot /var/www/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default
service nginx restart
