#!/usr/bin/env bash
#configure web-02 to be identical to web-01
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i "63i add_header X-Served-By $(echo `hostname`);" /etc/nginx/sites-available/default
service nginx restart

