#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using while loop

iterator=0

while [ $iterator -lt 10 ]; do
    echo "Holberton School"
    iterator=$(( iterator+1 )) 
done
