#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times using while loop with if

iterator=0

while [ $iterator -le 10 ]; do
    if [ $iterator -eq 9 ]; then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    iterator=$(( iterator+1 )) 
done
