#!/usr/bin/env bash
# This script is displaying number/string using while loop with conditions

iterator=1

while [ "$iterator" -le "20" ]; do
    echo "$iterator"
    case $iterator in 
	4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    iterator=$(( iterator+1 ))
done
