#!/usr/bin/env bash

iterator=0

while [ $iterator -le 20 ]; do
    echo "$iterator"
    case $iterator in 
	4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    iterator=$(( iterator+1 ))
done
