#!/usr/bin/env bash
# Run nginx under nginx user

sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
pkill apache2
chmod +r /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
