#!/usr/bin/env bash
# Run nginx under nginx user

pkill -f apache2
chmod +r /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
